# ----------------------- #
#     Site Variables      #
# ----------------------- #

name: Andreas Renberg (IQAndreas)
author: Andreas Renberg (IQAndreas)
url: 'http://www.www.you.can.basically.have.as.long.of.a.subdomain.as.you.want.iqandreas.com/'

title: "Welcme to www.www.you.can.basically.have.as.long.of.a.subdomain.as.you.want.iqandreas.com!"
displayed_title: "Welcome to"
subtitle: "www.www.you.can.basically.have.as.long.of.a.subdomain.as.you.want.iqandreas.com!"

#github_url: 'https://github.com/IQAndreas/www.www.you.can.basically.have.as.long.of.a.subdomain.as.you.want.iqandreas.com'
#github_username: IQAndreas

copyright_message: '<img src="/assets/images/trollface-100px.png">'
#github_license: The MIT License
#github_license_url: https://github.com/IQAndreas/markdown-licenses/blob/master/mit.md


# ----------------------- #
#       Site Paths        #
# ----------------------- #

# LOCAL
stylesheets: /assets/stylesheets
javascripts: /assets/javascripts
images:      /assets/images
fonts:       /assets/fonts

# GLOBAL
global_stylesheets: http://static.iqandreas.com/assets/stylesheets
global_javascripts: http://static.iqandreas.com/assets/javascripts
global_images:      http://static.iqandreas.com/assets/images
global_fonts:       http://static.iqandreas.com/assets/fonts

# ----------------------- #
#     Plugin Configs      #
# ----------------------- #

google_analytics_id:   UA-44446017-1
google_analytics_name: iqandreas.com

source_title_prefix: "GitHub: IQAndreas/www.www.you.can.basically.have.as.long.of.a.subdomain.as.you.want.iqandreas.com"
source_url: 'https://github.com/IQAndreas/www.www.you.can.basically.have.as.long.of.a.subdomain.as.you.want.iqandreas.com/tree/gh-pages'

# ----------------------- #
#     Jekyll Configs      #
# ----------------------- #

#source: source
destination: _public
plugins: 	 _plugins

exclude: [LICENSE.md]

relative_permalinks: false
markdown: redcarpet
pygments: true

